# Generated by Django 3.1.5 on 2021-01-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('json', models.FileField(upload_to='histories/json/')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='categoryID',
            field=models.PositiveIntegerField(),
        ),
    ]
