# Generated by Django 3.1.5 on 2021-01-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_history', '0002_auto_20210108_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
